name: father_delivery_user
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6


  # Set of Flutter Icons
  font_awesome_flutter: ^10.4.0

  # Packages for wrap, carousel slid ,animations ,dotted border and loading
  lottie: ^2.3.2
  dashed_circle: ^0.0.2
  animate_do: ^3.0.2
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  badges: ^3.1.1
  carousel_slider: ^4.2.1

  # Svg images , Picked and cache images packages
  flutter_svg: ^2.0.5
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3

  #Dropdown
  dropdown_button2: ^2.1.4

  # Otp Package
  pin_code_fields: ^7.4.0

  # Toast and output print
  fluttertoast: ^8.2.2
  quick_log: ^5.3.0

  # bloc for state management
  flutter_bloc: ^8.1.3

  # Value equality
  equatable: ^2.0.5

  #  Network and remote API
  dio: ^5.3.2
  url_launcher: ^6.1.11
  launch_review: ^3.0.1
  connectivity_plus: ^4.0.2

  # Service locator
  get_it: ^7.6.0

  # Local cache
  shared_preferences: ^2.2.0

  # Localization for language
  easy_localization: ^3.0.2

  # Adapting screen and font size
  flutter_screenutil: ^5.7.0

  # google maps
  #google_maps_flutter: ^2.1.1
  google_maps_flutter: ^2.2.8
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  permission_handler: ^10.2.0


  # rating star package
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

#   To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/svgs/
     - assets/translations/
     - assets/json/

  # To add custom fonts to your application, add a fonts section here,
  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/Cairo-Bold.ttf
           weight: 700
         - asset: assets/fonts/Cairo-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Cairo-Medium.ttf
           weight: 500
         - asset: assets/fonts/Cairo-Regular.ttf
           weight: 400